### PR TITLE
Check if refresh on model is a function

### PR DESCRIPTION
**Pull request by wwelling**
Resolves a regression introduced by https://github.com/TAMULib/Weaver-UI-Core/pull/232 where keydown escape event handler is invoked when a $scope.model.refresh method is not a function.

### CODE REVIEW

**Review by cstarcher — APPROVED** [review]
This fixes the three related issues. One issue I found while testing was some strange behavior  in modals with hidden elements (e.g. Add File). However, I think that is out of the scope of these issues and can be addressed separately.

File: package.json [hunk 1]
```diff
@@ -22,7 +22,7 @@
     "build": "wvr build --clean"
   },
   "dependencies": {
-    "@wvr/core": "2.2.4",
+    "@wvr/core": "https://github.com/TAMULib/Weaver-UI-Core.git#modal-keyboard-escape-fix",
```
Comment (kaladay) [inline package.json:25]: Be sure to revert/change this once weaver-ui-core is updated to the supporting weaver-ui-core release.

**Comment by wwelling** [comment]
Closing to recreate PR.
