### ISSUE TITLE
Download export to excel

### ISSUE THREAD

**Issue by nicksjunkyard** [TexasDigitalLibrary/Vireo#2098]
**Describe the bug**
I was filtering a list in vireo 4.3.1 and exporting it as an excel sheet. The download export popup goes away after a few seconds and a 500 error ribbon appears. Using the inspect menu in the browser displays an error.

XHRGET
https://vireo.ecu.edu/submission/batch-export/Excel
[HTTP/2 500  296ms]

	
meta	{ status: "ERROR", stacktrace: "org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.apache.poi.xssf.streaming.SXSSFWorkbook\r\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1086)\r\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)\r\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\r\n\tat org.spri…web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)\r\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)\r\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\r\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)\r\n\t... 87 more\r\n", action: null, … }
payload	{}

**To Reproduce**
1. Go to the list tab in your instance of vireo.
2. Apply a filter like approved items or a department name.
3. Click download export
4. Choose excel from the drop down and keep the active filter.
5. Click download export
6. See error

**Expected behavior**
The browser downloads the requested file format. In this case an excel spread sheet or csv file.

**Screenshots**
None

**Additional context**
Here is the vireo.log output during the process.
2025-08-12 09:00:32.151  INFO 2892 --- [https-openssl-nio-8443-exec-21] o.t.v.controller.SubmissionController    : Dynamic query took 0.1008266 seconds
2025-08-12 09:00:52.842  INFO 2892 --- [https-openssl-nio-8443-exec-23] o.t.v.controller.SubmissionController    : Beginning Export with packager Excel
2025-08-12 09:00:52.842  INFO 2892 --- [https-openssl-nio-8443-exec-23] o.t.v.controller.SubmissionController    : Cleaning up temp files for Excel
2025-08-12 09:00:52.842 ERROR 2892 --- [https-openssl-nio-8443-exec-23] c.a.CustomResponseEntityExceptionHandler : Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.apache.poi.xssf.streaming.SXSSFWorkbook

[tomcat9-stdout.2025-08-11.log](https://github.com/user-attachments/files/21738237/tomcat9-stdout.2025-08-11.log)

Thank you,
Nick

**Comment by jcross2562** [comment]
I am also experiencing this problem.

**Comment by nicksjunkyard** [comment]
I tried to build using maven 3.9.2 and the latest node js 22 LTS. I don't recommend attempting such a thing. Many node modules were reported as deprecated. I think node sass finally killed the build. I was hoping even though the old build was successful, it was missing something extra for certain types of downloadable packages.

<img width="1174" height="606" alt="Image" src="https://github.com/user-attachments/assets/32136a59-865f-43a8-800f-c90021e2bbef" />
